<DOCTYPE html>
<html>
    <head>
        <!--<link href="public/css/style.css" rel="stylesheet" type="text/css" />-->
        <!--<script type="text/javascript" src="public/js/javascript.js"></script>-->
        <!--<title>PAGE TITLE</title>-->
    </head>
    
    <body>
        <div class="main">
            <header>

            </header>

            <div class="content">
                    <?php 
                    require $this->view;
                    ?>

            </div>
            
                  <footer>
        <div>
          CSE/CIT480 - Database Design and Implementation <br>
          Kaseb Ahmed, Karan Chadha, Brandon Harden, Michael Looka, Shaifali Sood, Saadia Surti, and Ambika Vohra
        </div>
      </footer>
            
        </div>
        
    </body>
</html>
</DOCTYPE>