<!DOCTYPE html>
<html>
    <head>
        
        <title>ELECTRONIC MEDICAL RECORD</title>
        
        <?php 
        if($this->controller == "Person"){
        ?>
        <!-- CSS -->
        <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet"> 
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
        
        <?php if($this->action == "registerPerson") { ?>
        <link rel="stylesheet" href="public/css/registerstyle.css?<?php echo date('l jS \of F Y h:i:s A'); ?>">
        <?php } elseif($this->action == "loginPerson"){ ?>
        <link rel="stylesheet" href="public/css/loginstyle.css?<?php echo date('l jS \of F Y h:i:s A'); ?>">
        <?php } ?>
        
        <?php } else { ?>
        
        <!-- core CSS -->
    <link href="public/css/bootstrap.min.css?<?php echo date('l jS \of F Y h:i:s A'); ?>" rel="stylesheet">
    <link href="public/css/font-awesome.min.css?<?php echo date('l jS \of F Y h:i:s A'); ?>" rel="stylesheet">
    <link href="public/css/animate.min.css?<?php echo date('l jS \of F Y h:i:s A'); ?>" rel="stylesheet">
    <link href="public/css/prettyPhoto.css?<?php echo date('l jS \of F Y h:i:s A'); ?>" rel="stylesheet">
    <link href="public/css/main.css?<?php echo date('l jS \of F Y h:i:s A'); ?>" rel="stylesheet">
    <link href="public/css/responsive.css?<?php echo date('l jS \of F Y h:i:s A'); ?>" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="public/js/html5shiv.js"></script>
    <script src="public/js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="public/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="public/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="public/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="public/images/ico/apple-touch-icon-57-precomposed.png">
        
        <?php } ?>
        
        <link href="public/css/parsley.css?<?php echo date('l jS \of F Y h:i:s A'); ?>" rel="stylesheet">
    </head>
    
    <body>
            <script src="public/js/jquery.js"></script>
    <script src="public/js/jquery.prettyPhoto.js"></script>
    <script src="public/js/jquery.isotope.min.js"></script>
    <script src="public/js/jcombo.min.js"></script>
    <script src="public/js/parsley.js"></script>
        
        <?php if($this->controller != "Person") { ?>
    <script src="public/js/bootstrap.min.js"></script>
    <script src="public/js/main.js"></script>
    <script src="public/js/wow.min.js"></script>
    <?php } ?>
    
        <div class="main">
            <header>
                <?php if($this->controller != "Person"){ ?>
                
                <nav class="navbar navbar-inverse" role="banner">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.php"><img src="public/images/navlogofin.png" alt="logo"></a>
                </div>
				
                <div class="collapse navbar-collapse navbar-right">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="index.html">Home</a></li>
                        <li><a href="about-us.html">About Us</a></li>
                        <li><a href="services.html">Services</a></li>
                        <li><a href="portfolio.html">Portfolio</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Pages <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><a href="blog-item.html">Blog Single</a></li>
                                <li><a href="pricing.html">Pricing</a></li>
                                <li><a href="404.html">404</a></li>
                                <li><a href="shortcodes.html">Shortcodes</a></li>
                            </ul>
                        </li>
                        <li><a href="blog.html">Blog</a></li> 
                        <li><a href="contact-us.html">Contact</a></li>
                        <li><a href="<?php echo Utils::createLink('Person', 'logoutPerson'); ?>">Log Out</a></li>
                    </ul>
                </div>
            </div><!--/.container-->
        </nav><!--/nav-->
        
                <?php } ?>

            </header>

            <div class="content">
                    <?php
                    require $this->view;
                    ?>

            </div>
            
                  <footer <?php if($this->controller != "Person"){ echo ' id="footer" class="midnight-blue"'; } ?> >
                      <?php if($this->controller != "Person"){ ?>
                      <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2013 <a target="_blank" href="http://shapebootstrap.net/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">ShapeBootstrap</a>. All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About Us</a></li>
                        <li><a href="#">Faq</a></li>
                        <li><a href="#">Contact Us</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <?php } ?>
      </footer>
            
        </div>
        
        
    </body>
</html>