<form method="post" role="form" id="inboxView" action="#">

<div class="container_inbox">
    <div class="row">
        <div class="col-sm-3 col-md-2">
            <div class="btn-group">
              
            </div>
        </div>
        <div class="col-sm-9 col-md-10">
            <!-- Split button -->
            <div class="btn-group">
        
            </div>
          
            <!-- Single button -->
            <div class="btn-group">
               
            </div>
            <div class="pull-right">
                <span class="text-muted"></span>
                <div class="btn-group btn-group-sm">
              
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-3 col-md-2">
            <div data-toggle="modal" data-target="#modalCompose">
                     <br>
      <a id="open" href="#modalCompose" rel="modal:open" class="btn btn-danger btn-sm btn-block" role="button">COMPOSE</a>
      </div>
          
        </div>
        <div class="col-sm-9 col-md-10">
            <!-- Nav tabs -->
            <ul class="nav nav-tabs">
            </ul>
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane fade in active" id="home">
                    <div class="list-group">
                        
                        
                        
                        <?php
                        if(isset($my_inbox)){
                            foreach(array_reverse($my_inbox) as $msg){ ?>
                            
                            <a href="index.php?action=inboxOpen&controller=Messages&id=<?php echo $msg->getID(); ?>" class="list-group-item <?php if($msg->getIsRead() == 0){ echo "read"; } ?>">
                            <span class="name" style="min-width: 120px;
                                display: inline-block;"><?php echo $msg->getSenderFK()->getFullName(); ?></span> <span class=""><?php echo $msg->getSubject(); ?></span>
                            <span class="text-muted" style="font-size: 11px;">- <?php echo substr($msg->getMessage(), 0, 50); if(strlen($msg->getMessage()) >50) echo "..."; ?></span>  <span class="pull-right">
                                </span></a>
                            <?php    
                            }
                        }
                        ?>
  
                                                
                    </div>
                    
                </div>
                <div class="tab-pane fade in" id="profile">
                    <div class="list-group">
                        <div class="list-group-item">
                            <span class="text-center">This tab is empty.</span>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade in" id="messages">
                    ...</div>
                <div class="tab-pane fade in" id="settings">
                    This tab is empty.</div>
            </div>
            
        </div>
    </div>
  
  <!-- modalfor compose messag -->
    <div class="modal fade" id="modalCompose">
        
        
      <div class="modal-dialog">
        <div class="modal-content">
            
          <div class="modal-header">
            <button type="button" class="close hide-modal" data-dismiss="modal" aria-label="Close"><span aria-hidden="true" onclick="document.getElementById('id01').style.display='none'" 
        class="closebtn">&times;</span></button>
            <h4 class="modal-title">Compose Message</h4>
          </div>
          <div class="modal-body">
                <div class="form-group">
                  <label class="col-sm-2" for="inputTo">To</label>
                  <div class="col-sm-10"><select class="form-control" id="inputTo" name= "message[recipient_fk]" required></select></div>
                  <script> $(function() { $("#inputTo").jCombo("/apps/Messages/model/getRecipient.php?role=<?php echo $this->current_person->getRoleFK()->getID();?>");});</script>
                </div>
                
                <br>
                <div class="form-group">
                  <label class="col-sm-2" for="inputSubject">Subject</label>
                  <div class="col-sm-10"><input class="form-control" name="message[subject]" id="inputSubject" placeholder="subject" type="text" required></div>
                </div>
                
                <div class="form-group">
                  <label class="col-sm-12" for="inputBody">Message</label>
                  <div class="col-sm-12"><textarea class="form-control" name="message[message]" id="inputBody" rows="18" required></textarea></div>
                </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cancel</button> 
            <input type="submit" class="btn btn-primary " name="send_message" value="Send Message"></input>
            
          </div>
          
        </div><!-- /.modal-content -->
        
      </div><!-- /.modal-dialog -->
      
      
    </div><!-- /.modal compose message -->
  
  
</div>
<br><br><br><br><br><br><br><br>
<script>
$(document).ready(function(){
	$('.hide-modal').click(function(){
		$('modalCompose').modal('hide');
	}); 
});
</script>

</form>
 