    <div class="container">
        <center>
      <div class="section text-center">
        <h2 class="section-heading">Open New <span>Appointments</span></h2><hr>
      </div>  
      <div id="appointContain">
      <form class="form-horizontal" method='post' role="form" data-parsley-validate="" id="createappointmentsection" action="#">
        
        <br>
          <h4>
              <center>
                  <b>Select a date, and which appointment times you would like to be open to patients</b>
                  </center>
            </h4>
            
            <br>
            
            <div class="row">    
              <div class=container align="center">
                <div class="form-group">
                    <label>
                        Appointment Date:
                    </label>
              <table>
                  <thead></thead>
                  <tbody>
                      <tr>
                          <td valign="top">
                              
                  <input type="date" class="form-control date-pick" id="appointment_date" name="appointment_date" placeholder="Appointment Date" 
                  value="<?php
                                 echo $appointment_date;
                            ?>" required>
                            
                            <input type=hidden name="selected_date" value="<?php
                                  echo $appointment_date;
                            ?>">
                          </td>
                          <td valign="top">
                              <input style="margin-top:0;" class="btn btn-primary" id="submit" type="submit" name="goto" value="GO TO">
                          </td>
                      </tr>
                  </tbody>

              </table>
                </div>
              </div>
              
            
            <label>Appointment Times for <?php if($appointment_date){
                                  echo date('m/d/Y', strtotime($appointment_date));
                                  }
                            ?>:</label> 
            <br> </br>
            <button type="button" class="btn btn-danger"> Check All Times
            <input name="chk-all1[]" id="chk-all" type="checkbox">
            </button>
    </div>
    <div class= "row">
                  <!-- Morning Column -->
                  <div class= "col-md-4">
                  <div class="form-group">
                <!--    <center>  -->
                  <!--<div class="col-sm-4" style="margin:0px 430px;" align="center"> -->
  
  <h2> Morning </h2>
  <table class="table table-hover" id="medicationsTable">
            <thead>
                <tr>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($possible_times as $possible_time) 
                if($possible_time->getID() <=8 ){{ ?>
                    <tr>
                        <td>
                            <input name="<?php echo 'chk[' . $possible_time->getID() . ']'; ?>" 
                            type="checkbox"
                            <?php if (isset($selected_times)) {
                                    foreach ($selected_times as $selectd_time) {
                                        if ($selectd_time->getAppointmentTimeFK()->getID() == $possible_time->getId()) {
                                            echo "checked";
                                        }
                                    }
                                }
                            ?>>
                        </td>
                        <td>
                            <?php echo $possible_time->getTime(); ?>
                        </td>
                    </tr>
                <?php }
                } ?>
            </tbody>
        </table>
      </div>
    </div>
        <!-- Afternoon Column -->
            <div class= "col-md-4">
                  <div class="form-group">
  
             <h2> Afternoon </h2>
      <table class="table table-hover" id="medicationsTable">
            <thead>
            </thead>
            <tbody>
                <?php foreach ($possible_times as $possible_time) 
                if(($possible_time->getID() >=9) && ($possible_time->getID() <=26) ){{ ?>
                    <tr>
                        <td>
                            <input name="<?php echo 'chk[' . $possible_time->getID() . ']'; ?>" 
                            type="checkbox"
                            <?php if (isset($selected_times)) {
                                    foreach ($selected_times as $selectd_time) {
                                        if ($selectd_time->getAppointmentTimeFK()->getID() == $possible_time->getId()) {
                                            echo "checked";
                                        }
                                    }
                                }
                            ?>>
                        </td>
                        <td>
                            <?php echo $possible_time->getTime(); ?>
                        </td>
                    </tr>
                <?php }
                } ?>
            </tbody>
        </table>
      </div>
              
             
            </div>   
             
             <!-- Evening Column -->
             <div class="col-md-4">
                 <div class="form-group">
  
             <h2> Evening </h2>
      <table class="table table-hover" id="medicationsTable">
            <thead>
            </thead>
            <tbody>
                <?php foreach ($possible_times as $possible_time) 
                if(($possible_time->getID() >=27) && ($possible_time->getID() <=34) ){{ ?>
                    <tr>
                        <td>
                            <input name="<?php echo 'chk[' . $possible_time->getID() . ']'; ?>" 
                            type="checkbox"
                            <?php if (isset($selected_times)) {
                                    foreach ($selected_times as $selectd_time) {
                                        if ($selectd_time->getAppointmentTimeFK()->getID() == $possible_time->getId()) {
                                            echo "checked";
                                        }
                                    }
                                }
                            ?>>
                        </td>
                        <td>
                            <?php echo $possible_time->getTime(); ?>
                        </td>
                    </tr>
                <?php }
                } ?>
            </tbody>
        </table>
      </div>
              
             
            </div>         
            </div>
        <!-- Save Availability Code -->
            <center><input class="btn btn-primary" id="submit" type="submit" name="createAppointment" value="Save Available Appointments"></center><br>
          </form>
    </div>
    </div>
    </div>
    
    <br><br><br><br>
    
    <script>
    $("#chk-all").click(function () {
        $('input[name^=chk]').prop('checked', $(this).prop("checked"));
    });
    </script>