    <div class="container">
        <center>
      <div class="section text-center">
        <h2 class="section-heading">Open New <span>Appointments</span></h2><hr>
      </div>  
      <form class="form-horizontal" method='post' role="form" data-parsley-validate="" id="createappointmentsection" action="#">
<br>
          <h4><center><b>Select a date, and which appointment times you would like to open to patients</b></center></h4><br>
            <div class="row">    
              
              <div class="col-sm-4" style="margin:0px 430px;" align="middle">
                <div class="form-group">
                  <label><center>Appointment Date:</center></label>
                  <input type="date" class="form-control date-pick" id="appointmentdate" placeholder="Appointment Date" required>
                </div>
              </div>
              
            </div>
              
                <div class="form-group">
                    <center>
                        <div class="col-sm-4" style="margin:0px 430px;" align="center">
  <label>Appointment Times:</label>
  <table class="table table-hover" id="medicationsTable">
            <thead>
                <tr>
                    <th><input name="chk-all[]" type="checkbox"></th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($times as $time) { ?>
                    <tr>
                        <td>
                            <input name="chk[]" type="checkbox">
                            <input type="hidden" name="timeIDs[]" value='<?php echo $time->getID(); ?>'>
                        </td>
                        <td>
                            <?php echo $time->getTime(); ?>
                        </td>
                        
                    </tr>
                <?php } ?>
            </tbody>
        </table>
      </div>
              
              </center>
            </div>
            <center><button id="submit" type="submit" name="submit">Book Appointment</button></center><br>
          </form>
    </div>