
<form id="listPerson" action="#" method="post">
    <?php
    if (!isset($_GET['all'])) {
        Baseview::DisplayTitle('Active Users | <a href = "' . Utils::createLink($this->controller, $this->action, array('all' => true)) . '">All Users</a>');
    } else {
        Baseview::DisplayTitle('<a href = "' . Utils::createLink($this->controller, $this->action) . '">Active Users</a> | All Users');
    }
    if (empty($mylist)) {
        ?>
        <p>No Users found.</p>
        <?php
    } else {
        BaseView::DisplayTable($mylist, "index.php?controller=" . $this->controller . "&action=addeditPerson&id=");
    }
    ?>
</form>

