<div class="container">
<div class="section text-center">
        <h2 class="section-heading">My Records</span></h2>
        <hr>
</div>
<div id="listContain">
<form id="EMRPatient" action="#" method="post">
    <br>
    <div class="form-group">
        <table style=width:100%;>
    <center><?php
    $tablefield = new FieldTable();
    $tablefield->setClass('col-lg-8');
    $tablefield->setID('myTable');
    $tablefield->setValue($mylist);
    $tablefield->setNav("index.php?controller=EMR&action=EMRView&appointment_id=");
    $tablefield->ShowField();
    ?></center>
    </table>
    </div>
</form>
</div>
</div>

<script>
    function DoNav(the_link, new_window) {
    if (new_window === undefined) {
        document.location.href = the_link;
    } else {
        var windowresult = window.open("");
        windowresult.location.href = the_link;
    }
}
</script>