<section id="banner" class="banner">
		<div class="bg-color">
			<div class="container">
				<div class="row">
					<div class="banner-info">
						<div class="banner-logo text-center">
							<!-- <img src="/public/images/homepage/logo.png" class="img-responsive"> -->
						</div>
						<div class="banner-text text-center">
							<h3 style="color:white">Your centralized application for all of your medical needs, whether you're a patient or a physician.</h3>
							<a href="#contact" class="btn btn-appoint">Get started with PocketEMR.</a>
						</div>
						<div class="overlay-detail text-center">
			               <a href="#service"><i class="fa fa-angle-down"></i></a>
			             </div>		
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--/ banner-->
	<!--service-->
	<section id="service" class="section-padding">
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-sm-4">
					<h2 class="ser-title">Our Service</h2>
					<p>PocketEMR provides services for physicians and doctors to communicate effectively. Physicians can view upcoming appointments, fill out an EMR, send messages to patients, and view patient info from the comfort of one centralized application. Similarly, patients can search for physicians, schedule an appointment, view physician info, and send messages to physicians. PocketEMR synthesizes the day to day operations of a patient-physician relationship into a smooth process.</p>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="service-info">
						<div class="icon">
							<i class="fa fa-stethoscope"></i>
						</div>
						<div class="icon-info">
							<h4>Support</h4>
							<p>We provide ways to streamline the process of communication between a patient and a physician.</p>
						</div>
					</div>
					<div class="service-info">
						<div class="icon">
							<i class="fa fa-ambulance"></i>
						</div>
						<div class="icon-info">
							<h4>Why PocketEMR</h4>
							<p>Other EMR systems may have the convenience of electronically completing medical info, but only PocketEMR integrates the patient-physician relationship into the process. Rather than separating two inherently connected processes, PocketEMR's goal is to make patient visits painless, intuitive, and as accessible as your pocket.</p>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4">
					<div class="service-info">
						<div class="icon">
							<i class="fa fa-user-md"></i>
						</div>
						<div class="icon-info">
							<h4>Medical Expertise</h4>
							<p>PocketEMR has physicians from all around the nation registered with their profiles ready to view. You can view things like a physician's education, residency location, and specialization to make sure you're getting the care you need. </p>
						</div>
					</div>
					<div class="service-info">
						<div class="icon">
							<i class="fa fa-medkit"></i>
						</div>
						<div class="icon-info">
							<h4>Premium Connectivity</h4>
							<p>Want to reschedule an appointment? Have a question? These simple issues would cause an array of missed phone calls or contact attempts. Through PocketEMR, patients and physicians can directly contact each other without any hassle.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--/ service-->
	<!--cta-->
	<section id="cta-1" class="section-padding">
		<div class="container">
			<div class="row">
				<div class="schedule-tab">
    			<div class="col-md-4 col-sm-4 bor-left">
    				<div class="mt-boxy-color"></div>
	    			<div class="medi-info">
		    			<h3>PocketEMR News</h3>
						<p>A new feature has been added to PocketEMR! You can now send messages to physicians and easily find physicians in your area. These messages will allow for quicker communication!</p>
						<!--<a href="#" class="medi-info-btn">READ MORE</a>		    	-->
					</div>
    			</div>
				<div class="col-md-4 col-sm-4">
					<div class="medi-info">
		    			<h3>PocketEMR News</h3>
						<p>PocketEMR recently got featured in Tech Savvy's 10 Best Apps for Medicine! As our user count grows, we have found that more and more are recognizing the simplicity of keeping medical info and scheduling visits all in one place.</p>
						<!--<a href="#" class="medi-info-btn">READ MORE</a>	-->
					</div>
				</div>
				<div class="col-md-4 col-sm-4 mt-boxy-3">
					<div class="mt-boxy-color"></div>
					<div class="time-info">
			    			<h3>Contact Our HQ</h3>
							<table style="margin: 8px 0px 0px;" border="1">
								<tbody>
									<tr>
									<td>Monday - Friday</td>
									<td>8.00 - 17.00</td>
									</tr>
									<tr>
									<td>Saturday</td>
									<td>9.30 - 17.30</td>
									</tr>
									<tr>
									<td>Sunday</td>
									<td>9.30 - 15.00</td>
									</tr>
								</tbody>
							</table>				    		
					</div>
				</div>
				</div>
			</div>
		</div>
	</section>
	<!--cta-->
	<!--about-->
	<section id="about" class="section-padding">
		<div class="container">
			<div class="row">
				<div class="col-md-3 col-sm-4 col-xs-12">
			        <div class="section-title">
			          <h2 class="head-title lg-line">PocketEMR<br>Ultimate Goal</h2>
			          <br>
			          <p class="sec-para">Our goal is to allow patients and physicians to have an easier time with visits. There is an end-to-end line of communication between both parties, that streamlines care to the fullest.</p>
			          <!--<a href="" style="color: #0cb8b6; padding-top:10px;">Know more..</a>-->
			        </div>
			    </div>
			    <div class="col-md-9 col-sm-8 col-xs-12">
			       <div style="visibility: visible;" class="col-sm-9 more-features-box">
			          <div class="more-features-box-text">
			            <div class="more-features-box-text-icon"> <i class="fa fa-angle-right" aria-hidden="true"></i> </div>
			            <div class="more-features-box-text-description">
				            <h3>We Care About Patients</h3>
				            <p>We understand that patient time is valuable - PocktEMR allows you to accomplish more in a faster time!</p>
				        </div>
			          </div>
			          <div class="more-features-box-text">
			            <div class="more-features-box-text-icon"> <i class="fa fa-angle-right" aria-hidden="true"></i> </div>
			            <div class="more-features-box-text-description">
				            <h3>We Care About Physicians</h3>
				            <p>Physicians see so many patients per day - its important they can streamline the process and keep all the info in one place.</p>
				        </div>
                        </div>
			        </div>
			    </div>
			</div>
		</div>
	</section>
	<!--/ about-->
	<!--doctor team-->
	<section id="doctor-team" class="section-padding">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h2 class="ser-title">Featured Doctors!</h2>
					<hr class="botm-line">
				</div>
				<div class="col-md-3 col-sm-3 col-xs-6">
			      <div class="thumbnail"> 
			      	<img src="/public/images/homepage/doctor1.jpg" alt="..." class="team-img">
			        <div class="caption">
			          <h3>Jessica Wally</h3>
			          <p>Doctor</p>
			          <ul class="list-inline">
			            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
			            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
			            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
			          </ul>
			        </div>
			      </div>
			    </div>
			    <div class="col-md-3 col-sm-3 col-xs-6">
			      <div class="thumbnail"> 
			      	<img src="/public/images/homepage/doctor2.jpg" alt="..." class="team-img">
			        <div class="caption">
			          <h3>Iai Donas</h3>
			          <p>Doctor</p>
			          <ul class="list-inline">
			            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
			            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
			            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
			          </ul>
			        </div>
			      </div>
			    </div>
			    <div class="col-md-3 col-sm-3 col-xs-6">
			      <div class="thumbnail"> 
			      	<img src="/public/images/homepage/doctor3.jpg" alt="..." class="team-img">
			        <div class="caption">
			          <h3>Amanda Denyl</h3>
			          <p>Doctor</p>
			          <ul class="list-inline">
			            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
			            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
			            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
			          </ul>
			        </div>
			      </div>
			    </div>
			    <div class="col-md-3 col-sm-3 col-xs-6">
			      <div class="thumbnail"> 
			      	<img src="/public/images/homepage/doctor4.jpg" alt="..." class="team-img">
			        <div class="caption">
			          <h3>Jason Davis</h3>
			          <p>Doctor</p>
			          <ul class="list-inline">
			            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
			            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
			            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
			          </ul>
			        </div>
			      </div>
			    </div>
			</div>
		</div>
	</section>
	<!--/ doctor team-->
	<!--testimonial-->
	<section id="testimonial" class="section-padding">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h2 class="ser-title">See what patients are saying?</h2>
				</div>
				<br><br>
				<div class="col-md-4 col-sm-4">
					<div class="testi-details">
						<!-- Paragraph -->
						<p>No more waiting in lines or long phone calls. PocketEMR gives me just what I need when I need it!</p>
					<div class="testi-info">
						<!-- User Image -->
						<a href="#"><img src="/public/images/homepage/thumb.png" alt="" class="img-responsive"></a>
						<!-- User Name -->
						<h3>Alex<span>Texas</span></h3>
					</div>
				</div>
			</div>
			
				<div class="col-md-4 col-sm-4">
					<div class="testi-details">
						<!-- Paragraph -->
						<p>Where was this five years ago? I think something like this would have really helped me with my annual checkups.</p>
					<div class="testi-info">
						<!-- User Image -->
						<a href="#"><img src="/public/images/homepage/thumb.png" alt="" class="img-responsive"></a>
						<!-- User Name -->
						<h3>Corinne<span>Dolloway</span></h3>
					</div>
				</div>
			</div>
			
				<div class="col-md-4 col-sm-4">
					<div class="testi-details">
						<!-- Paragraph -->
						<p>I feel like my care is so much faster and personalized! I could not have asked for a better medical application for me to use.</p>
					<div class="testi-info">
						<!-- User Image -->
						<a href="#"><img src="/public/images/homepage/thumb.png" alt="" class="img-responsive"></a>
						<!-- User Name -->
						<h3>Jean<span>Smith</span></h3>
					</div>
				</div>
			</div>
		</div>
		</div>
	</section>
	<!--/ testimonial-->
	<!--cta 2-->
	<section id="cta-2" class="section-padding">
		<div class="container">
			<div class=" row">
				<div class="col-md-2"></div>
	            <div class="text-right-md col-md-4 col-sm-4">
	              <h2 class="section-title white lg-line"> A few words<br> about us </h2>
	            </div>
	            <div class="col-md-4 col-sm-5">
	             <p>Established in 2017, PocketEMR is a brand new application that allows physicians and patients to effectively communicate.</p> 
	              <p class="text-right text-primary"><i>PocketEMR</i></p>
	            </div>
	            <div class="col-md-2"></div>
	        </div>
		</div>
	</section>
	<!--cta-->
	<!--contact-->
	<!--<section id="contact" class="section-padding">-->
	<!--	<div class="container">-->
	<!--		<div class="row">-->
	<!--			<div class="col-md-12">-->
	<!--				<h2 class="ser-title">Contact us</h2>-->
	<!--				<br>-->
	<!--			</div>-->
	<!--			<div class="col-md-4 col-sm-4">-->
	<!--		      <h3>Contact Info</h3>-->
	<!--		      <div class="space"></div>-->
	<!--		      <p><i class="fa fa-map-marker fa-fw pull-left fa-2x"></i>321 Awesome Street<br>-->
	<!--		        New York, NY 17022</p>-->
	<!--		      <div class="space"></div>-->
	<!--		      <p><i class="fa fa-envelope-o fa-fw pull-left fa-2x"></i>info@pocketemr.com</p>-->
	<!--		      <div class="space"></div>-->
	<!--		      <p><i class="fa fa-phone fa-fw pull-left fa-2x"></i>+1 800 123 1234</p>-->
	<!--		    </div>-->
	<!--			<div class="col-md-8 col-sm-8 marb20">-->
	<!--				<div class="contact-info">-->
	<!--						<h3 class="cnt-ttl">Ask Us A Question!</h3>-->
	<!--						<div class="space"></div>-->
 <!--                           <div id="sendmessage">Your message has been sent. Thank you!</div>-->
 <!--                           <div id="errormessage"></div>-->
	<!--						<form action="" method="post" role="form" class="contactForm">-->
	<!--						    <div class="form-group">-->
 <!--                                   <input type="text" name="name" class="form-control br-radius-zero" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />-->
 <!--                                   <div class="validation"></div>-->
 <!--                               </div>-->
 <!--                               <div class="form-group">-->
 <!--                                   <input type="email" class="form-control br-radius-zero" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />-->
 <!--                                   <div class="validation"></div>-->
 <!--                               </div>-->
 <!--                               <div class="form-group">-->
 <!--                                   <input type="text" class="form-control br-radius-zero" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />-->
 <!--                                   <div class="validation"></div>-->
 <!--                               </div>-->
 <!--                               <div class="form-group">-->
 <!--                                   <textarea class="form-control br-radius-zero" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>-->
 <!--                                   <div class="validation"></div>-->
 <!--                               </div>-->
                                
	<!--							<div class="form-action">-->
	<!--								<button type="submit" class="btn btn-form">Send Message</button>-->
	<!--							</div>-->
	<!--						</form>-->
	<!--				</div>-->
	<!--			</div>-->
	<!--		</div>-->
	<!--	</div>-->
	<!--</section>-->
	<!--/ contact-->
	<!--footer-->
	<!--<footer id="footer">-->
	<!--	<div class="top-footer">-->
	<!--		<div class="container">-->
	<!--			<div class="row">-->
	<!--				<div class="col-md-4 col-sm-4 marb20">-->
	<!--						<div class="ftr-tle">-->
	<!--							<h4 class="white no-padding">About Us</h4>-->
	<!--						</div>-->
	<!--						<div class="info-sec">-->
	<!--							<p>PocketEMR is revolutionizing the way patients and doctors interact.</p>-->
	<!--						</div>-->
	<!--				</div>-->
	<!--				<div class="col-md-4 col-sm-4 marb20">-->
	<!--					<div class="ftr-tle">-->
	<!--						<h4 class="white no-padding">Quick Links</h4>-->
	<!--					</div>-->
	<!--					<div class="info-sec">-->
	<!--						<ul class="quick-info">-->
	<!--							<li><a href="index.html"><i class="fa fa-circle"></i>Home</a></li>-->
	<!--							<li><a href="#service"><i class="fa fa-circle"></i>Service</a></li>-->
	<!--							<li><a href="#contact"><i class="fa fa-circle"></i>Appointment</a></li>-->
	<!--						</ul>-->
	<!--					</div>-->
	<!--				</div>-->
	<!--				<div class="col-md-4 col-sm-4 marb20">-->
	<!--					<div class="ftr-tle">-->
	<!--						<h4 class="white no-padding">Follow us</h4>-->
	<!--					</div>-->
	<!--					<div class="info-sec">-->
	<!--						<ul class="social-icon">-->
	<!--							<li class="bglight-blue"><i class="fa fa-facebook"></i></li>-->
	<!--							<li class="bgred"><i class="fa fa-google-plus"></i></li>-->
	<!--							<li class="bgdark-blue"><i class="fa fa-linkedin"></i></li>-->
	<!--							<li class="bglight-blue"><i class="fa fa-twitter"></i></li>-->
	<!--						</ul>-->
	<!--					</div>-->
	<!--				</div>-->
	<!--			</div>-->
	<!--		</div>-->
	<!--	</div>-->
	<!--	<div class="footer-line">-->
	<!--		<div class="container">-->
	<!--			<div class="row">-->
	<!--				<div class="col-md-12 text-center">-->
 <!--                       <div class="credits">-->